### ISSUE TITLE
IntersectionObserver sometimes looses events on Chrome/ Opera

### ISSUE THREAD

**Issue by damac23** [ApoorvSaxena/lozad.js#91] opened 2018-03-09 07:38 UTC
The initial problem: This is extremly hard to reproduce and I too have reports for Firefox that I cannot confirm.

So sometimes in a list of let's say 20 images one or two aren't loaded. The data-loaded is not set, so if you scroll the element out of view and back again it will be loaded.

I've tried to find recent bugreports for Chrome, but was not lucky.
The only thing that came near my observation is this ticket: https://github.com/firehol/netdata/issues/3289

Does anyone encountered similar behavior?
If so: Is there some kind of workaround w/o falling back to the old ways?

**Comment by fkwakkenbos** [comment] 2018-03-09 12:54
@damac23 I'm experiencing the same issue. Using Chrome 65.0.3325.146. 

Although i'm not having the issue on Chrome Canary 67.0.3366.0, so it seems it is a issue related to Chrome.

**Comment by akkis** [comment] 2018-03-15 16:39
I can confirm that with Google Chrome 65.0.3325.162 I have a lot of issues with the appearance of the images, while Firefox 60.0b3 works fine.

**Comment by ApoorvSaxena** [comment] 2018-03-18 12:09
Closing this issue, as needs to be fixed at the browser's end

**Closed by ApoorvSaxena** 2018-03-18 12:09 UTC

**Comment by fintinc** [comment] 2019-03-22 18:15
Hi 
I'm having issues with the latest version of Chrome on OSX and Windows. Only about half of the images are loaded, many are not loaded at all. 
Maybe it has something to do that the images are only visible on hover (css opacity).

The solution that works for me is to add a src attribute with a placeholder image:
`<img class="lozad" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="myimg.jpg">`

Maybe this is useful for somebody.
