### ISSUE TITLE
React Support?

### ISSUE THREAD

**Issue by pixelcure** [ApoorvSaxena/lozad.js#55] opened 2017-10-10 20:23 UTC
I was wondering if Lozad works with react? I'm currently having trouble getting it work, I was trying to utilize lifecycle methods and have it not start observing until after the component is rendered. However, it seems like based on the nature of react and vdom, it doesn't actually work because my component is rendered before Lozad is initialized.

Any ideas? I was trying something along the lines of:

```
    observer = lozad('.lozad', {
        load: function() { console.log('loaded'); }
    });

    componentDidMount() {
        this.observer.observe();
    }
```

Thanks in advanced!

**Comment by styfle** [comment] 2017-10-11 20:14
@ApoorvSaxena Does lozad accept a dom element instead of a selector?

If so, you could do something like the following:

```js
class LozadWrapper extends React.Component {
  componentDidMount() {
    const observer = lozad(this.img, {
      rootMargin: '10px 0px', // syntax similar to that of CSS Margin
      threshold: 0.1 // ratio of element convergence
    });
    observer.observe();
  }

  render() {
    const  { src, srcset } = this.props;
    return (
      <img ref={(el) => this.img = el} data-src={src} data-srcset={srcset} />
    );
  }
}

ReactDOM.render(<LozadWrapper src="image.png" srcset="image.png 1000w, image-2x.png 2000w" />, someRootElement);
```

**Comment by PezCoder** [comment] 2017-10-16 19:07
I would like to work on this.

I can think of two approaches to implement it:
1. Either accept two different types in first parameter i.e either a dom node or a selector which I think is not a great idea for a variable to have two completely different type of values.
2. Another way is to pass the dom node in options as the second parameter but It'll be confusing to determine what will happen with both first & second parameters being present.

Any help on how to go about doing this ?

**Comment by styfle** [comment] 2017-10-16 19:39
> Either accept two different types in first parameter i.e either a dom node or a selector which I think is not a great idea for a variable to have two completely different type of values.

Why not? This is what jQuery does. You can say `$('.some-class')` or you can say `$(document.getElementById('some-id'))`. This is commonly used inside an event handler like so:

```js
$('.btn').click(function() {
  $(this).css('color', 'purple'); // make the clicked button purple
});
```
```

**Comment by ApoorvSaxena** [comment] 2017-10-17 04:37
@PezCoder I agree with @styfle, you can go ahead with approach 1, of using either a dom node or a selector.

Regarding:

> Another way is to pass the dom node in options as the second parameter but It'll be confusing to determine what will happen with both selector & DOM node present.

Options is not the right place to pass selector or DOM element as it's not a configuration setting.

> To accept just the selector but somehow keep track of dynamically inserted selector, something like what jquery's $.on() does. That should keep the library usage the same but should make everything work with frameworks/libraries that inject the elements later in the page i.e after lozad's initialisation.

This is performance intensive task, may even bloat the library size if using a dependency.

**Comment by PezCoder** [comment] 2017-10-17 18:02
Agree, @ApoorvSaxena @styfle The first approach seems optimal, I'll create a PR right away.

**Comment by pixelcure** [comment] 2017-10-17 19:16
Thanks guys! Then, we can add a reference on the image within your react component and pass that to lozad as opposed to a class?

@PezCoder @ApoorvSaxena 

Let me know if I can help in any way 😃

**Comment by PezCoder** [comment] 2017-10-17 20:24
I think i went in wrong order of doing things.. 😅

@pixelcure I setup a quick react application with create-react-app
& did this:
```js
  constructor() {
    super();
    this.observer = lozad();
  }

  componentDidMount() {
    this.observer.observe();
  }
  
  render() {
    return (
      <img data-src={logo} className="App-logo lozad" alt="logo" />
    );
  }
```
This seems to be working fine, I got this DOM node inside my html
```html
<img data-src="/static/media/logo.5d5d9eef.svg" class="App-logo lozad" alt="logo" src="/static/media/logo.5d5d9eef.svg" data-loaded="true">
```
i.e with src & data-loaded = true.. 

Can you create a plunker/jsbin with minimal set of instructions that reproduces your specific issue ?

**Comment by ApoorvSaxena** [comment] 2017-10-17 21:11
@PezCoder do you mind sharing the react implementation in plunker/jsbin yourself?

**Comment by PezCoder** [comment] 2017-10-17 22:02
Codepen:
https://codepen.io/PezCoder/pen/mBaOer

Lesson learnt: To not dive in for a solution without verifying the issue first 😄

**Comment by ApoorvSaxena** [comment] 2017-10-18 06:12
@pixelcure can you verify the solution as proposed by @PezCoder?

**Comment by ApoorvSaxena** [comment] 2017-10-20 08:10
closing this issue for now

**Closed by ApoorvSaxena** 2017-10-20 08:10 UTC
Labels: enhancement, hacktoberfest, help wanted, question

**Comment by meotimdihia** [comment] 2019-04-03 08:04
Can't get `rootMargin` option work with the @PezCoder example.

**Comment by blainemuri** [comment] 2020-01-15 21:20
It would be nice to reopen this discussion with an example of how to do this without `componentDidMount` so that it can work with the new react-hooks paradigm.

**Comment by sean-clayton** [comment] 2020-02-14 04:59
@blainemuri Here's a custom hook I made that should do the trick.

```js
import { useEffect } from "react";
import lozad from "lozad";

function useLozad(selector, options) {
  useEffect(() => {
    const observer = lozad(selector, options);
    observer.observe();
  }, [selector, options]);
}
```

And here's a CodeSandbox demo: https://codesandbox.io/s/suspicious-wilson-dj2oq

**Comment by vamcs** [comment] 2023-01-11 16:26
Remember to clean up the subscription when using it in a `useEffect`:

```typescript
useEffect(() => {
  const { observe, observer } = lozad()
  observe()
  return () => observer.disconnect()
}, [])
```
